# Generated by Django 3.0.7 on 2020-10-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_uid', models.IntegerField()),
                ('u_name', models.CharField(max_length=100)),
            ],
        ),
    ]
