# Generated by Django 3.0.7 on 2020-10-22 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_application', '0002_auto_20201022_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makes',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_application.User'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='Users',
            field=models.ManyToManyField(through='database_application.Makes', to='database_application.User'),
        ),
    ]
