# Generated by Django 3.1.2 on 2020-10-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_application', '0003_auto_20201022_0630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Users',
            field=models.ManyToManyField(through='database_application.Makes', to='database_application.User'),
        ),
    ]
